### ISSUE TITLE
Make hovered nodes easier to find by using a different background

### ISSUE THREAD

**Issue by ADTC** [anvaka/sayit#56]
Currently the hovered nodes are difficult to find as they only have a pink border.

<img width="720" alt="image" src="https://github.com/user-attachments/assets/7d20d2f8-92ea-4a85-bca9-0f2c614b3032">

It will be nice if the hovered border can be pink background instead, with white text. It's easier to find.

<img width="905" alt="image" src="https://github.com/user-attachments/assets/40576fda-62b0-4cb7-a240-ba171ec46740">

CSS changes:

```css
.hovered rect, path.hovered {
    /* stroke: #ff4081; */
    fill: #ff4081;
}

.hovered text {
    fill: white;
}
```
